# https://github.com/M0hammedImran

window:
  dimensions:
    columns: 80
    lines: 30
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  Values for `decorations`:
    - none: Neither borders nor title bar

  # Window title
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 3

  # Font configuration
font:
  # Normal (roman) font face
  normal:
    family: Cascadia Code
    style: Regular

  # Bold font face
  bold:
    family: Cascadia Code
    style: Bold

  # Italic font face
  italic:
    family: Fira Code
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Fira Code
    style: Bold Italic

  # Point size
  size: 11.0

  # Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  # Normal colors
  normal:
    black: '#000000'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#caa9fa'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#bfbfbf'

  # Bright colors
  bright:
    black: '#575b70'
    red: '#ff6e67'
    green: '#5af78e'
    yellow: '#f4f99d'
    blue: '#caa9fa'
    magenta: '#ff92d0'
    cyan: '#9aedfe'
    white: '#e6e6e6'

  cursor:
    text: CellBackground
    cursor: CellForeground

  selection:
    text: CellBackground
    background: CellForeground

  search:
    matches:
      foreground: '#000000'
      background: '#ffffff'
    focused_match:
      foreground: CellBackground
      background: CellForeground

    bar:
      background: '#c5c8c6'
      foreground: '#1d1f21'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

style: Bloc

shell:
  program: /bin/zsh
  
  url:
   
    Default:
      - (Linux/BSD) xdg-open
    
    launcher:
      program: xdg-open
    
key_bindings:
  - { key: Paste,                                action: Paste          }
  - { key: Copy,                                 action: Copy           }
  - { key: L,         mods: Control,             action: ClearLogNotice }
  - { key: L,         mods: Control, mode: ~Vi,  chars: "\x0c"          }
  - { key: PageUp, mods: Shift, mode: ~Alt, action: ScrollPageUp }
  - { key: PageDown, mods: Shift, mode: ~Alt, action: ScrollPageDown }
  - { key: Home, mods: Shift, mode: ~Alt, action: ScrollToTop }
  - { key: End, mods: Shift, mode: ~Alt, action: ScrollToBottom }
