# https://github.com/M0hammedImran

window:
  dimensions:
    columns: 80
    lines: 30
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  Values for `decorations`:
    - none: Neither borders nor title bar

  # Window title
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 3

  # Font configuration
font:
  # Normal (roman) font face
  normal:
    family: JetBrains Mono
    style: Regular

  # Bold font face
  bold:
    family: JetBrains Mono
    style: Bold

  # Italic font face
  italic:
    family: JetBrains Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    family: JetBrains Mono
    style: Bold Italic

  # Point size
  size: 12.0

# Lighthaus Color theme for Alacritty
# GIT: https://github.com/lighthaus-theme/alacritty
# Author: Adhiraj Sirohi (https://github.com/brutuski)
#         Vasundhara Sharma (https://github.com/vasundhasauras)

# Copyright © 2020-Present Lighthaus Theme
# Copyright © 2020-Present Adhiraj Sirohi
# Copyright © 2020-Present Vasundhara Sharma


colors:
  # Default colors
  primary:
    background: '#18191E'
    foreground: '#FFEE79'
  
  selection:
    text:       '#FF4D00'
    background: '#090B26'

  # Cursor colors
  cursor:
    text:       '#18191E'
    cursor:     '#FFFF00'

  # Normal colors
  normal:
    black:      '#18191E'
    red:        '#FC2929'
    green:      '#44B273'
    yellow:     '#E25600'
    blue:       '#1D918B'
    magenta:    '#D16BB7'
    cyan:       '#00BFA4'
    white:      '#CCCCCC'

  # Bright colors
  bright:
    black:      '#21252D'
    red:        '#FF5050'
    green:      '#50C16E'
    yellow:     '#ED722E'
    blue:       '#47A8A1'
    magenta:    '#D68EB2'
    cyan:       '#5AD1AA'
    white:      '#FFFADE'

  cursor:
    text: CellBackground
    cursor: CellForeground

  selection:
    text: CellBackground
    background: CellForeground

  search:
    matches:
      foreground: '#000000'
      background: '#ffffff'
    focused_match:
      foreground: CellBackground
      background: CellForeground

    bar:
      background: '#c5c8c6'
      foreground: '#1d1f21'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

style: Bloc

shell:
  program: /usr/bin/fish

  url:
    Default:
      - (Linux/BSD) xdg-open

    launcher:
      program: xdg-open

key_bindings:
  - { key: Paste, action: Paste }
  - { key: Copy, action: Copy }
  - { key: L, mods: Control, action: ClearLogNotice }
  - { key: L, mods: Control, mode: ~Vi, chars: "\x0c" }
  - { key: PageUp, mods: Shift, mode: ~Alt, action: ScrollPageUp }
  - { key: PageDown, mods: Shift, mode: ~Alt, action: ScrollPageDown }
  - { key: Home, mods: Shift, mode: ~Alt, action: ScrollToTop }
  - { key: End, mods: Shift, mode: ~Alt, action: ScrollToBottom }
