format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$rust\
$golang\
$package\
$docker_context\
$line_break\
$battery\
$time\
$status\
$character
"""

[git_status]
conflicted = "🏳 "
ahead = "🏎 💨 "
behind = "😰 "
diverged = "😵 "
untracked = "🤷 "
stashed = "📦 "
modified = "📝 "
staged = '[++\($count\)](green)'
renamed = "👅 "
deleted = "🗑 "

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[docker_context]
disabled = false
format = "via [🐋 $context](blue bold)"

[time]
disabled = false
format = '🕙 [\[ $time \]]($style)' 
time_format = "%T"
utc_time_offset = "+5.50"
time_range = "00:00:00-23:59:59"

[battery]
disabled = false
full_symbol = "🔋 "
charging_symbol = "⚡️"
discharging_symbol = "💀 "

[git_branch]
disabled = false
symbol = "🌱 "

[git_commit]
disabled = false
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
disabled = false
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[golang]
disabled = false
format = "via [🏎💨 $version](bold cyan) "
